baseURL = 'https://htgaa.bioclub.tokyo/'
languageCode = 'en-us'
title = 'HTGAA @BioClub Tokyo'
github = 'https://github.com/owner/repo'

# https://gohugo.io/getting-started/configuration-markup/
[markup]
  defaultMarkdownHandler = 'goldmark'
[markup.goldmark.renderer]
  unsafe = true

[security]
  enableInlineShortcodes = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
